version: "3.7"

services:
  postgres:
    container_name: postgres
    image: mdillon/postgis:10-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - /node/postgres:/var/lib/postgresql/data:z
    environment:
      POSTGRES_USER: node
      POSTGRES_PASSWORD: node
      POSTGRES_DB: node
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 127.0.0.1:6379:6379
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - /node/redis:/data:z
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root